//
//  AIService.swift
//  Striv
//
//  Created by Thibault Giraudon on 05/03/2026.
//

import Foundation
import FirebaseAI

/// Service responsible for generating AI analysis for workouts.
///
/// `AIService` acts as an intermediary between the application
/// and the AI provider. It validates prerequisites such as
/// network availability before delegating the request to
/// `AIRepository`.
///
/// Responsibilities:
/// - Check network connectivity before sending requests
/// - Forward analysis requests to the AI repository
/// - Map low-level errors to domain-specific `AIError`
final class AIService {
    
    /// Repository responsible for communicating with the AI provider.
    private let aiRepository: AIRepository
    
    /// Utility used to monitor network connectivity.
    private let networkMonitor: NetworkMonitor
    
    /// Creates a new `AIService`.
    ///
    /// - Parameters:
    ///   - aiRepository: Repository used to communicate with the AI backend.
    ///   - networkMonitor: Utility used to verify network availability.
    ///   Default instances are provided but can be injected for testing.
    init(aiRepository: AIRepository = .init(), networkMonitor: NetworkMonitor = .init()) {
        self.aiRepository = aiRepository
        self.networkMonitor = networkMonitor
    }
    
    /// Generates an AI analysis for the given workout.
    ///
    /// This method first verifies that the device has an active
    /// network connection. If the connection is unavailable,
    /// an `AIError.connection` error is thrown.
    ///
    /// If the network is available, the workout prompt is sent
    /// to the AI provider through `AIRepository`.
    ///
    /// Errors coming from the AI provider are mapped to
    /// domain-specific `AIError` values.
    ///
    /// - Parameter workout: The workout to analyze.
    /// - Returns: A textual analysis generated by the AI.
    /// - Throws: `AIError.connection` if no network is available,
    ///   `AIError.internalAI` if the AI provider fails,
    ///   or `AIError.invalid` for any unexpected error.
    func analyze(_ workout: Workout) async throws -> String {
        guard networkMonitor.execute() else {
            throw AIError.connection
        }

        do {
            return try await aiRepository.askGemini(with: workout.analyzePrompt)
        } catch is GenerateContentError {
            throw AIError.internalAI
        } catch {
            throw AIError.invalid
        }
    }
}
