//
//  AIRepository.swift
//  Striv
//
//  Created by Thibault Giraudon on 17/12/2025.
//

import Foundation
import FirebaseAI

/// Repository responsible for interacting with the AI backend.
///
/// `AIRepository` provides a thin abstraction over the AI provider.
/// It is responsible for sending user input to the AI model and
/// returning the generated text.
///
/// Responsibilities:
/// - Select the AI model to use (`gemini-2.5-flash-lite`)
/// - Forward text input to the AI backend
/// - Decode the AI response
/// - Map low-level decoding errors to `AIDecodeError`
class AIRepository {
    
    /// AI service instance provided by FirebaseAI.
    private let ai = FirebaseAI.firebaseAI(backend: .googleAI())
    
    private var aiConsentAccepted: Bool {
        get {
            UserDefaults.standard.bool(forKey: "aiConsentAccepted")
        }
        
        set {
            UserDefaults.standard.set(newValue, forKey: "aiConsentAccepted")
        }
    }
    
    /// The generative model used to process user input.
    private var model: GenerativeModel {
        ai.generativeModel(modelName: "gemini-2.5-flash-lite")
    }
    
    /// Sends a text input to the AI model and returns the generated output.
    ///
    /// This method forwards the input to the `GenerativeModel` and
    /// returns the resulting text. If the model response cannot
    /// be decoded, an `AIDecodeError` is thrown.
    ///
    /// - Parameter input: The text input to send to the AI model.
    /// - Returns: The text generated by the AI model.
    /// - Throws:
    ///   - `AIDecodeError.wrongType` if the response type is unexpected
    ///   - `AIDecodeError.missingKey` if a required key is missing in the response
    ///   - `AIDecodeError.unknown` for any other decoding failure
    func askGemini(with input: String) async throws -> String {
        guard aiConsentAccepted else {
            throw AIConsentError.consentRequired
        }
        
        let response = try await model.generateContent(input)
                
        guard let text = response.text else {
            throw AIDecodeError.unknown
        }
        
        return text
    }
}

enum AIConsentError: Error {
    case consentRequired
}

/// Errors that can occur when decoding AI responses.
enum AIDecodeError: Swift.Error, LocalizedError, Hashable {
    /// The AI response type was not as expected.
    case wrongType
    /// A required key was missing from the AI response.
    case missingKey
    /// Unknown decoding error.
    case unknown
    
    var errorDescription: String? {
        switch self {
        case .wrongType: return "The AI response was of the wrong type."
        case .missingKey: return "A required key is missing from the AI response."
        case .unknown: return "An unknown error occurred while decoding the AI response."
        }
    }
}
